# Generated by Django 5.0.6 on 2024-05-15 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100, verbose_name='Car model')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Модели машин',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год выпуска машины')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Контактные данные для связи')),
                ('damage_description', models.TextField(blank=True, null=True, verbose_name='Описание повреждения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.carmodel', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
                'ordering': ('id',),
            },
        ),
    ]
